markdown: kramdown
permalink: /:year/:month/:day/:title/
url: https://yuocai.github.io
author: yuocai
highlighter: rouge
safe: true
auto: true
future: true
paginate: 25
gems: [jekyll-paginate]
kramdown:
    toc_levels: 1..3
